version: '3'
services:  
  dev:
    image: maven:3.5.2-jdk-8-alpine    
    volumes:
      - ".:/usr/src/app/"     
      # Cache maven dependencies 
      - "$HOME/.maven-docker/:/root/.m2/"  
    ports:
     - "8080:8080"
    command:       
      - '/bin/bash'
      - '-c'
      - '(cd /usr/src/app && mvn spring-boot:run)'            

  builder:    
    image: maven:3.5.2-jdk-8-alpine    
    volumes:
      - ".:/usr/src/app/"        
      - "$HOME/.maven-docker/:/root/.m2/"
    command:
      - 'mvn'
      - '-f'
      - '/usr/src/app/pom.xml' 
      - 'package'     

  app:
    build: .
    ports:
     - "8080:8080"